### ISSUE TITLE
Feature request: default codependency

### ISSUE THREAD

**Issue by benmccann** [Wizcorp/codependency#17]
I would like the user to include a date-library (i.e. one of moment, luxon, or date-fns). I'm not sure if it's possible, but if the user doesn't manually include one, then it'd be nice if I could specify one to be automatically included as the default.

**Comment by ronkorving** [comment]
You mean you would want to ship your package with one of those libraries as a dependency, to be used if the user does not supply one? Or where exactly would that default package come from?

**Comment by benmccann** [comment]
Hmm. Maybe not possible. I'm not quite sure how it would work
