### ISSUE TITLE
Does not support nested modules.

### ISSUE THREAD

**Issue by Raynos** [Wizcorp/codependency#4]
``` js
var requirePeer = codependency.register(module);
var createRingPopTChannel =
    require('ringpop/lib/tchannel.js').createRingPopTChannel;
```

I cannot use `requirePeer` to pull a module inside a package out of it.

I presume all the isInstalled logic needs to be changed to support this use case.

cc @ronkorving

**Comment by ronkorving** [comment]
You mean you want to require a file that is inside a peer dependency? (in your example `require` would be `requirePeer`?)

**Comment by Raynos** [comment]
@ronkorving correct. I changed it back to require to get my code working.

But it should work with requirepeer.

**Comment by ronkorving** [comment]
Thanks for the feedback. That's definitely worth addressing. Think you could PR that yourself? (I'm a bit busy lately, but might have a crack at it later)

**Comment by ronkorving** [comment]
It's been a while, sorry for not responding to this before, but #7 should have fixed this. Closing this issue. Let me know if there are still issues.
