### ISSUE TITLE
Incompatible with Yarn

### ISSUE THREAD

**Issue by spencer-brown** [Wizcorp/codependency#9]
This package is a transitive dependency of my project that occurs in multiple locations within my project's dependency tree.

When I run my server (whose dependencies have been installed with [Yarn](https://yarnpkg.com/en/)), I see this error:

<img width="1010" alt="screen shot 2017-03-28 at 3 42 20 pm" src="https://cloud.githubusercontent.com/assets/5354793/24430780/349a56b6-13cd-11e7-806f-f9823f5faad3.png">

I think this error results from Yarn's deduping of dependencies. Yarn only installs a single copy of a package of a particular version, which in this case is causing the "middleware already registered" error to be thrown.

cc @ronkorving - thanks! :)

**Comment by ronkorving** [comment]
So when you install with NPM, this problem does not occur?

**Comment by spencer-brown** [comment]
@ronkorving Correct (though I've only tried with npm 2.15.9 -- I'm not sure about other versions).

**Comment by ronkorving** [comment]
I don't have any issues, and have been using `codependency` over the years on NPM 2 - latest, so NPM should be fine. That is, assuming your project doesn't have a very weird dependency resolution situation going on that I have yet to encounter (whatever that may be).

Mind debugging this to figure out what's going on *exactly* here? I think deduping should be a *good* thing for codependency, not a bad thing. If anything, it would be the lack of deduping (the inability to) that might cause problems.

**Comment by ronkorving** [comment]
Due to inactivity, I'm going to close this issue. Let me know if you wanna get back on this.
